/** Baraja tradicional de 54 cartas con el verso del gritón. */
export const CARTAS: { id: number; nombre: string; verso: string }[] = [
  { id: 1, nombre: 'El Gallo', verso: 'El que le cantó a San Pedro no le volverá a cantar.' },
  { id: 2, nombre: 'El Diablito', verso: 'Pórtate bien cuatito, si no te lleva el coloradito.' },
  { id: 3, nombre: 'La Dama', verso: 'Puliendo el paso, por toda la calle real.' },
  { id: 4, nombre: 'El Catrín', verso: 'Don Ferruco en la alameda, su bastón quería tirar.' },
  { id: 5, nombre: 'El Paraguas', verso: 'Para el sol y para el agua.' },
  { id: 6, nombre: 'La Sirena', verso: 'Con los cantos de sirena, no te vayas a marear.' },
  { id: 7, nombre: 'La Escalera', verso: 'Súbeme paso a pasito, no quieras pegar brinquitos.' },
  { id: 8, nombre: 'La Botella', verso: 'La herramienta del borracho.' },
  { id: 9, nombre: 'El Barril', verso: 'Tanto bebió el albañil, que quedó como barril.' },
  { id: 10, nombre: 'El Árbol', verso: 'El que a buen árbol se arrima, buena sombra le cobija.' },
  { id: 11, nombre: 'El Melón', verso: 'Me lo das o me lo quitas.' },
  { id: 12, nombre: 'El Valiente', verso: 'Por qué le corres cobarde, trayendo tan buen puñal.' },
  { id: 13, nombre: 'El Gorrito', verso: 'Ponle su gorrito al nene, no se nos vaya a resfriar.' },
  { id: 14, nombre: 'La Muerte', verso: 'La muerte tilica y flaca.' },
  { id: 15, nombre: 'La Pera', verso: 'El que espera, desespera.' },
  { id: 16, nombre: 'La Bandera', verso: 'Verde, blanco y colorado, la bandera del soldado.' },
  { id: 17, nombre: 'El Bandolón', verso: 'Tocando su bandolón, está el mariachi Simón.' },
  { id: 18, nombre: 'El Violoncello', verso: 'Creciendo se fue hasta el cielo, y como no fue violín, tuvo que ser violoncello.' },
  { id: 19, nombre: 'La Garza', verso: 'Al otro lado del río tengo mi banco de arena.' },
  { id: 20, nombre: 'El Pájaro', verso: 'Tú me traes a puros brincos, como pájaro en la rama.' },
  { id: 21, nombre: 'La Mano', verso: 'La mano de un criminal.' },
  { id: 22, nombre: 'La Bota', verso: 'Una bota igual que la otra.' },
  { id: 23, nombre: 'La Luna', verso: 'El farol de los enamorados.' },
  { id: 24, nombre: 'El Cotorro', verso: 'Cotorro cotorro saca la pata, y empiézame a platicar.' },
  { id: 25, nombre: 'El Borracho', verso: 'A qué borracho tan necio, ya no lo puedo aguantar.' },
  { id: 26, nombre: 'El Negrito', verso: 'El que se comió el azúcar.' },
  { id: 27, nombre: 'El Corazón', verso: 'No me extrañes corazón, que regreso en el camión.' },
  { id: 28, nombre: 'La Sandía', verso: 'La barriga que Juan tenía, era empacho de sandía.' },
  { id: 29, nombre: 'El Tambor', verso: 'No te arrugues, cuero viejo, que te quiero pa tambor.' },
  { id: 30, nombre: 'El Camarón', verso: 'Camarón que se duerme, se lo lleva la corriente.' },
  { id: 31, nombre: 'Las Jaras', verso: 'Las jaras del indio Adán, donde pegan, dan.' },
  { id: 32, nombre: 'El Músico', verso: 'El músico trompas de hule, ya no me quiere tocar.' },
  { id: 33, nombre: 'La Araña', verso: 'Atarántamela a palos, no me la dejes llegar.' },
  { id: 34, nombre: 'El Soldado', verso: 'Uno, dos y tres, el soldado p al cuartel.' },
  { id: 35, nombre: 'La Estrella', verso: 'La guía de los marineros.' },
  { id: 36, nombre: 'El Cazo', verso: 'El caso que te hago es poco.' },
  { id: 37, nombre: 'El Mundo', verso: 'Este mundo es una bola, y nosotros un bolón.' },
  { id: 38, nombre: 'El Apache', verso: 'Ah Chihuahua! Cuánto apache con pantalón y huarache.' },
  { id: 39, nombre: 'El Nopal', verso: 'Al nopal lo van a ver, nomás cuando tiene tunas.' },
  { id: 40, nombre: 'El Alacrán', verso: 'El que con la cola pica, le dan una paliza.' },
  { id: 41, nombre: 'La Rosa', verso: 'Rosita, Rosaura, ven que te quiero ahora.' },
  { id: 42, nombre: 'La Calavera', verso: 'Al pasar por el panteón, me encontré un calaverón.' },
  { id: 43, nombre: 'La Campana', verso: 'Tú con la campana y yo con tu hermana.' },
  { id: 44, nombre: 'El Cantarito', verso: 'Tanto va el cántaro al agua, que se quiebra y te moja las enaguas.' },
  { id: 45, nombre: 'El Venado', verso: 'Saltando va buscando, pero no ve nada.' },
  { id: 46, nombre: 'El Sol', verso: 'La cobija de los pobres.' },
  { id: 47, nombre: 'La Corona', verso: 'El sombrero de los reyes.' },
  { id: 48, nombre: 'La Chalupa', verso: 'Rema que rema Lupita, sentada en su chalupita.' },
  { id: 49, nombre: 'El Pino', verso: 'Fresco y oloroso, en todo tiempo hermoso.' },
  { id: 50, nombre: 'El Pescado', verso: 'El que por la boca muere, aunque mudo fuere.' },
  { id: 51, nombre: 'La Palma', verso: 'Palmero, sube a la palma y bájame un coco real.' },
  { id: 52, nombre: 'La Maceta', verso: 'El que nace pa maceta, no sale del corredor.' },
  { id: 53, nombre: 'El Arpa', verso: 'Arpa vieja de mi suegra, ya no sirves pa tocar.' },
  { id: 54, nombre: 'La Rana', verso: 'Al ver a la verde rana, qué brinco pegó tu hermana.' },
];
