/** Skins iniciales. Las de precio 0 se canjean gratis y son el look por defecto. */
export const SKINS: { tipo: 'ficha' | 'carta'; clave: string; nombre: string; descripcion: string; precio_puntos: number; rareza: 'comun' | 'rara' | 'epica' | 'legendaria' }[] = [
  { tipo: 'ficha', clave: 'frijol', nombre: 'Frijolito', descripcion: 'El clásico de toda la vida', precio_puntos: 0, rareza: 'comun' },
  { tipo: 'ficha', clave: 'maiz', nombre: 'Grano de maíz', descripcion: 'Amarillo y brillante', precio_puntos: 50, rareza: 'comun' },
  { tipo: 'ficha', clave: 'piedrita', nombre: 'Piedrita de río', descripcion: 'Lisa y gris', precio_puntos: 80, rareza: 'comun' },
  { tipo: 'ficha', clave: 'corcholata', nombre: 'Corcholata', descripcion: 'De refresco de vidrio', precio_puntos: 120, rareza: 'rara' },
  { tipo: 'ficha', clave: 'chile', nombre: 'Chilito', descripcion: 'Pica al marcar', precio_puntos: 200, rareza: 'rara' },
  { tipo: 'ficha', clave: 'calaverita', nombre: 'Calaverita de azúcar', descripcion: 'Con tu nombre en la frente', precio_puntos: 300, rareza: 'epica' },
  { tipo: 'ficha', clave: 'moneda_oro', nombre: 'Moneda de oro', descripcion: 'Brilla en cada casilla', precio_puntos: 500, rareza: 'legendaria' },
  // Animales nacionales
  { tipo: 'ficha', clave: 'ajolote', nombre: 'Ajolote', descripcion: 'Sonriente, de los canales de Xochimilco', precio_puntos: 150, rareza: 'rara' },
  { tipo: 'ficha', clave: 'colibri', nombre: 'Colibrí', descripcion: 'Rápido como tus marcas', precio_puntos: 150, rareza: 'rara' },
  { tipo: 'ficha', clave: 'mariposa_monarca', nombre: 'Mariposa monarca', descripcion: 'Llega volando desde Michoacán', precio_puntos: 180, rareza: 'rara' },
  { tipo: 'ficha', clave: 'tortuga', nombre: 'Tortuga marina', descripcion: 'De las playas de Oaxaca', precio_puntos: 180, rareza: 'rara' },
  { tipo: 'ficha', clave: 'xolo', nombre: 'Xoloitzcuintle', descripcion: 'El perrito que guía a las almas', precio_puntos: 280, rareza: 'epica' },
  { tipo: 'ficha', clave: 'jaguar', nombre: 'Jaguar', descripcion: 'Señor de la selva maya', precio_puntos: 350, rareza: 'epica' },
  { tipo: 'ficha', clave: 'quetzal', nombre: 'Quetzal', descripcion: 'Plumas de jade', precio_puntos: 450, rareza: 'legendaria' },
  { tipo: 'ficha', clave: 'aguila', nombre: 'Águila real', descripcion: 'La del escudo nacional', precio_puntos: 600, rareza: 'legendaria' },
  { tipo: 'carta', clave: 'clasica', nombre: 'Clásica', descripcion: 'Ilustración tradicional', precio_puntos: 0, rareza: 'comun' },
  { tipo: 'carta', clave: 'papel_picado', nombre: 'Papel picado', descripcion: 'Bordes de fiesta', precio_puntos: 150, rareza: 'rara' },
  { tipo: 'carta', clave: 'dia_muertos', nombre: 'Día de Muertos', descripcion: 'Cempasúchil y catrinas', precio_puntos: 300, rareza: 'epica' },
  { tipo: 'carta', clave: 'lucha_libre', nombre: 'Lucha libre', descripcion: 'Cada carta con máscara', precio_puntos: 400, rareza: 'epica' },
  { tipo: 'carta', clave: 'neon', nombre: 'Neón', descripcion: 'Estilo cantina de noche', precio_puntos: 600, rareza: 'legendaria' },
  // Lugares, artesanías y fauna de México
  { tipo: 'carta', clave: 'talavera', nombre: 'Talavera poblana', descripcion: 'Azulejo azul de Puebla', precio_puntos: 200, rareza: 'rara' },
  { tipo: 'carta', clave: 'caribe', nombre: 'Caribe mexicano', descripcion: 'Olas turquesa de Tulum', precio_puntos: 200, rareza: 'rara' },
  { tipo: 'carta', clave: 'ajolote_lago', nombre: 'Lago del ajolote', descripcion: 'Burbujas de Xochimilco', precio_puntos: 220, rareza: 'rara' },
  { tipo: 'carta', clave: 'xochimilco', nombre: 'Trajinera', descripcion: 'Franjas de colores sobre el canal', precio_puntos: 250, rareza: 'rara' },
  { tipo: 'carta', clave: 'monarca', nombre: 'Santuario monarca', descripcion: 'Alas naranjas de Michoacán', precio_puntos: 300, rareza: 'epica' },
  { tipo: 'carta', clave: 'chichen_itza', nombre: 'Chichén Itzá', descripcion: 'Escalones de la pirámide de Kukulkán', precio_puntos: 350, rareza: 'epica' },
  { tipo: 'carta', clave: 'alebrije', nombre: 'Alebrije', descripcion: 'Colores imposibles de Oaxaca', precio_puntos: 400, rareza: 'epica' },
  { tipo: 'carta', clave: 'selva_jaguar', nombre: 'Selva del jaguar', descripcion: 'Manchas de la selva lacandona', precio_puntos: 450, rareza: 'epica' },
  { tipo: 'carta', clave: 'bellas_artes', nombre: 'Bellas Artes', descripcion: 'Art déco negro y oro', precio_puntos: 700, rareza: 'legendaria' },
];
